services:
  - type: web
    name: telegram-bot-hosting
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python index.py
    envVars:
      - key: MAIN_BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: REQUIRED_CHANNEL
        value: -1003710820481
      - key: WEBHOOK_BASE_URL
        value: https://telegram-bot-hosting.onrender.com
      - key: PYTHON_VERSION
        value: 3.11.0